// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Link struct {
	ID          int64         `json:"id"`
	PortfolioID sql.NullInt64 `json:"portfolio_id"`
	Title       string        `json:"title"`
	Url         string        `json:"url"`
}

type Portfolio struct {
	ID      int64          `json:"id"`
	Photo   sql.NullString `json:"photo"`
	Aboutme sql.NullString `json:"aboutme"`
}

type Project struct {
	ID          int64        `json:"id"`
	PortfolioID int64        `json:"portfolio_id"`
	Title       string       `json:"title"`
	StartDate   sql.NullTime `json:"start_date"`
	EndDate     sql.NullTime `json:"end_date"`
}

type Skill struct {
	ID          int64  `json:"id"`
	PortfolioID int64  `json:"portfolio_id"`
	Title       string `json:"title"`
	Progress    string `json:"progress"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
