// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (Portfolio, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteLink(ctx context.Context, id int64) error
	DeletePortfolio(ctx context.Context, id int64) error
	DeleteProject(ctx context.Context, id int64) error
	DeleteSkill(ctx context.Context, id int64) error
	GetLinks(ctx context.Context, portfolioID sql.NullInt64) ([]Link, error)
	GetPortfolio(ctx context.Context, id int64) (Portfolio, error)
	GetPortfolioForUpdate(ctx context.Context, id int64) (Portfolio, error)
	GetProjects(ctx context.Context, portfolioID int64) ([]Project, error)
	GetSkills(ctx context.Context, portfolioID int64) ([]Skill, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListPortfolios(ctx context.Context, arg ListPortfoliosParams) ([]Portfolio, error)
	UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error)
	UpdatePortfolio(ctx context.Context, arg UpdatePortfolioParams) (Portfolio, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error)
}

var _ Querier = (*Queries)(nil)
